# Generated by Django 5.2.7 on 2025-10-16 13:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagem_alter_autor_biogr_alter_editora_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path_capa),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='capas'),
        ),
    ]
